"""Ampliato idD del docente

Revision ID: 32849ebc363a
Revises: 2f4962c11e0b
Create Date: 2023-07-21 00:50:37.344552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32849ebc363a'
down_revision = '2f4962c11e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('docente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idD', sa.String(length=200), nullable=False))
        batch_op.create_unique_constraint(None, ['idD'])
        batch_op.drop_column('idD')  # Corrected column name to 'idD'

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ids', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('idS')

    with op.batch_alter_table('prova', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idd', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('idp', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ide', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('prova_ide_fkey', 'esame', ['ide'], ['ide'])
        batch_op.create_foreign_key('prova_idd_fkey', 'docente', ['idd'], ['idd'])
        batch_op.drop_column('idD')
        batch_op.drop_column('idE')
        batch_op.drop_column('idP')

    with op.batch_alter_table('esame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ide', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('idE')

    with op.batch_alter_table('docente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idd', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('idD')

    op.create_table('appelli',
    sa.Column('idp', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('ids', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('voto', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stato_superamento', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idp'], ['prova.idp'], name='appelli_idp_fkey'),
    sa.ForeignKeyConstraint(['ids'], ['studente.ids'], name='appelli_ids_fkey'),
    sa.PrimaryKeyConstraint('idp', 'ids', name='appelli_pkey')
    )
    op.create_table('registrazione_esame',
    sa.Column('ids', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ide', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('voto', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_superamento', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ide'], ['esame.ide'], name='registrazione_esame_ide_fkey'),
    sa.ForeignKeyConstraint(['ids'], ['studente.ids'], name='registrazione_esame_ids_fkey'),
    sa.PrimaryKeyConstraint('ids', 'ide', name='registrazione_esame_pkey')
    )
    op.create_table('creazione_esame',
    sa.Column('idd', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('ide', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('ruolo_docente', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idd'], ['docente.idd'], name='creazione_esame_idd_fkey'),
    sa.ForeignKeyConstraint(['ide'], ['esame.ide'], name='creazione_esame_ide_fkey'),
    sa.PrimaryKeyConstraint('idd', 'ide', name='creazione_esame_pkey')
    )
    op.drop_table('Appelli')
    op.drop_table('Registrazione_esame')
    op.drop_table('Creazione_esame')
    # ### end Alembic commands ###
