"""aggiunto cfu e anno accademico

Revision ID: 362917f0163e
Revises: 
Create Date: 2023-05-16 15:05:32.930528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362917f0163e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('esame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cfu', sa.Integer(), nullable=True))
        batch_op.alter_column('idE',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('idD',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('CFU')

    with op.batch_alter_table('registrazione_esame', schema=None) as batch_op:
        batch_op.drop_column('data_superamento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrazione_esame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_superamento', sa.DATE(), nullable=True))

    with op.batch_alter_table('esame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CFU', sa.INTEGER(), nullable=True))
        batch_op.alter_column('idD',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('idE',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('cfu')

    # ### end Alembic commands ###
