"""aggiunto foreign key alla tabella studenti

Revision ID: 39c4822d9fa9
Revises: d7e9c7a8de34
Create Date: 2023-06-11 11:28:36.594485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c4822d9fa9'
down_revision = 'd7e9c7a8de34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idP', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key('fk_studente_prova_idP', 'prova', ['idP'], ['idP'])

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('idP')

    op.create_table('registrazione_esame',
    sa.Column('idS', sa.INTEGER(), nullable=False),
    sa.Column('idE', sa.INTEGER(), nullable=False),
    sa.Column('voto', sa.INTEGER(), nullable=True),
    sa.Column('data_superamento', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['idE'], ['esame.idE'], ),
    sa.ForeignKeyConstraint(['idS'], ['studente.idS'], ),
    sa.PrimaryKeyConstraint('idS', 'idE')
    )
    op.create_table('appelli',
    sa.Column('idE', sa.INTEGER(), nullable=False),
    sa.Column('idS', sa.INTEGER(), nullable=False),
    sa.Column('voto', sa.INTEGER(), nullable=True),
    sa.Column('stato_superamento', sa.BOOLEAN(), nullable=True)
    )
    op.create_table('creazione_esame',
    sa.Column('idD', sa.INTEGER(), nullable=False),
    sa.Column('idE', sa.INTEGER(), nullable=False),
    sa.Column('ruolo_docente', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['idD'], ['docente.idD'], ),
    sa.ForeignKeyConstraint(['idE'], ['esame.idE'], ),
    sa.PrimaryKeyConstraint('idD', 'idE')
    )
    op.drop_table('Registrazione_esame')
    op.drop_table('Appelli')
    op.drop_table('Creazione_esame')
    # ### end Alembic commands ###
