"""primo

Revision ID: 3b65ec77cb41
Revises: 
Create Date: 2023-07-22 22:07:40.129640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b65ec77cb41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ids', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('idS')

    with op.batch_alter_table('prova', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('tipo_prova',
               existing_type=sa.Enum('scritto', 'orale', 'pratico', 'completo', name='tipo_prova'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)

    with op.batch_alter_table('esame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ide', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('idE')

    with op.batch_alter_table('docente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idd', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('idD')

    with op.batch_alter_table('Appelli', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('idP',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.create_table('creazione_esame',
    sa.Column('idd', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('ide', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('ruolo_docente', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idd'], ['docente.idd'], name='creazione_esame_idd_fkey'),
    sa.ForeignKeyConstraint(['ide'], ['esame.ide'], name='creazione_esame_ide_fkey'),
    sa.PrimaryKeyConstraint('idd', 'ide', name='creazione_esame_pkey')
    )
    op.create_table('registrazione_esame',
    sa.Column('ids', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ide', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('voto', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_superamento', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ide'], ['esame.ide'], name='registrazione_esame_ide_fkey'),
    sa.ForeignKeyConstraint(['ids'], ['studente.ids'], name='registrazione_esame_ids_fkey'),
    sa.PrimaryKeyConstraint('ids', 'ide', name='registrazione_esame_pkey')
    )
    op.drop_table('Registrazione_esame')
    op.drop_table('Creazione_esame')
    # ### end Alembic commands ###
