"""aggiunto percentuale

Revision ID: 4deddb51d465
Revises: 39245d043e58
Create Date: 2023-06-23 23:09:26.188368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4deddb51d465'
down_revision = '39245d043e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prova', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentuale', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prova', schema=None) as batch_op:
        batch_op.drop_column('percentuale')

    with op.batch_alter_table('Appelli', schema=None) as batch_op:
        batch_op.alter_column('idP',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.create_table('registrazione_esame',
    sa.Column('idS', sa.INTEGER(), nullable=False),
    sa.Column('idE', sa.INTEGER(), nullable=False),
    sa.Column('voto', sa.INTEGER(), nullable=True),
    sa.Column('data_superamento', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['idE'], ['esame.idE'], ),
    sa.ForeignKeyConstraint(['idS'], ['studente.idS'], ),
    sa.PrimaryKeyConstraint('idS', 'idE')
    )
    op.create_table('creazione_esame',
    sa.Column('idD', sa.INTEGER(), nullable=False),
    sa.Column('idE', sa.INTEGER(), nullable=False),
    sa.Column('ruolo_docente', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['idD'], ['docente.idD'], ),
    sa.ForeignKeyConstraint(['idE'], ['esame.idE'], ),
    sa.PrimaryKeyConstraint('idD', 'idE')
    )
    op.create_table('_alembic_tmp_Appelli',
    sa.Column('idS', sa.INTEGER(), nullable=False),
    sa.Column('idE', sa.VARCHAR(length=100), nullable=False),
    sa.Column('voto', sa.INTEGER(), nullable=True),
    sa.Column('stato_superamento', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['idE'], ['esame.idE'], ),
    sa.ForeignKeyConstraint(['idS'], ['studente.idS'], )
    )
    op.drop_table('Registrazione_esame')
    op.drop_table('Creazione_esame')
    # ### end Alembic commands ###
