"""your_migration_message_here

Revision ID: 8c65ceb3d0e8
Revises: 4deddb51d465
Create Date: 2023-07-21 00:27:33.221562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c65ceb3d0e8'
down_revision = '4deddb51d465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Appelli')
    op.drop_table('prova')
    op.drop_table('Registrazione_esame')
    op.drop_table('Creazione_esame')
    op.drop_table('studente')
    op.drop_table('esame')
    op.drop_table('docente')
    # ### end Alembic commands ###
