"""aggiunto ora della prova al database

Revision ID: a171a943b3ee
Revises: 091b0c90a1de
Create Date: 2023-06-08 15:43:18.634138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a171a943b3ee'
down_revision = '091b0c90a1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('prova', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ora_prova', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prova', schema=None) as batch_op:
        batch_op.drop_column('ora_prova')

    with op.batch_alter_table('esame', schema=None) as batch_op:
        batch_op.alter_column('idE',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               autoincrement=True)

    op.create_table('registrazione_esame',
    sa.Column('idS', sa.INTEGER(), nullable=False),
    sa.Column('idE', sa.INTEGER(), nullable=False),
    sa.Column('voto', sa.INTEGER(), nullable=True),
    sa.Column('data_superamento', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['idE'], ['esame.idE'], ),
    sa.ForeignKeyConstraint(['idS'], ['studente.idS'], ),
    sa.PrimaryKeyConstraint('idS', 'idE')
    )
    op.create_table('creazione_esame',
    sa.Column('idD', sa.INTEGER(), nullable=False),
    sa.Column('idE', sa.INTEGER(), nullable=False),
    sa.Column('ruolo_docente', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['idD'], ['docente.idD'], ),
    sa.ForeignKeyConstraint(['idE'], ['esame.idE'], ),
    sa.PrimaryKeyConstraint('idD', 'idE')
    )
    op.create_table('_alembic_tmp_esame',
    sa.Column('idE', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=True),
    sa.Column('anno_accademico', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cfu', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('idE'),
    sa.UniqueConstraint('idE')
    )
    op.create_table('appelli',
    sa.Column('idE', sa.INTEGER(), nullable=False),
    sa.Column('idS', sa.INTEGER(), nullable=False),
    sa.Column('voto', sa.INTEGER(), nullable=True),
    sa.Column('stato_superamento', sa.BOOLEAN(), nullable=True)
    )
    op.drop_table('Registrazione_esame')
    op.drop_table('Creazione_esame')
    op.drop_table('Appelli')
    # ### end Alembic commands ###
