"""sistemato foreign key della tabella esame

Revision ID: db4026ad5f1a
Revises: 362917f0163e
Create Date: 2023-05-16 15:36:56.076329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db4026ad5f1a'
down_revision = '362917f0163e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('idE')

    with op.batch_alter_table('esame', schema=None) as batch_op:
        batch_op.alter_column('idD',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('esame', schema=None) as batch_op:
        batch_op.alter_column('idD',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('docente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idE', sa.VARCHAR(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'esame', ['idE'], ['idE'])

    # ### end Alembic commands ###
