"""aggiunto tipo prova alla tabella prova

Revision ID: ec7605a5d877
Revises: f70be1cb00a9
Create Date: 2023-05-19 16:22:31.287689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7605a5d877'
down_revision = 'f70be1cb00a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Appelli', schema=None) as batch_op:
        batch_op.drop_column('tipo_prova')

    with op.batch_alter_table('Prova', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_prova', sa.Enum('scritto', 'orale', 'pratico'), nullable=True))

    # ... add any other required changes ...

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prova', schema=None) as batch_op:
        batch_op.drop_column('tipo_prova')

    with op.batch_alter_table('esame', schema=None) as batch_op:
        batch_op.alter_column('idE',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               autoincrement=True)

    op.create_table('creazione_esame',
    sa.Column('idD', sa.INTEGER(), nullable=False),
    sa.Column('idE', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['idD'], ['docente.idD'], ),
    sa.ForeignKeyConstraint(['idE'], ['esame.idE'], ),
    sa.PrimaryKeyConstraint('idD', 'idE')
    )
    op.create_table('registrazione_esame',
    sa.Column('idS', sa.INTEGER(), nullable=False),
    sa.Column('idE', sa.INTEGER(), nullable=False),
    sa.Column('voto', sa.INTEGER(), nullable=True),
    sa.Column('data_superamento', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['idE'], ['esame.idE'], ),
    sa.ForeignKeyConstraint(['idS'], ['studente.idS'], ),
    sa.PrimaryKeyConstraint('idS', 'idE')
    )
    op.create_table('appelli',
    sa.Column('idE', sa.INTEGER(), nullable=False),
    sa.Column('idS', sa.INTEGER(), nullable=False),
    sa.Column('data_superamento', sa.DATE(), nullable=True),
    sa.Column('data_scadenza', sa.DATE(), nullable=True),
    sa.Column('voto', sa.INTEGER(), nullable=True),
    sa.Column('stato_superamento', sa.BOOLEAN(), nullable=True),
    sa.Column('tipo_prova', sa.VARCHAR(length=7), nullable=True),
    sa.ForeignKeyConstraint(['idE'], ['esame.idE'], ),
    sa.ForeignKeyConstraint(['idS'], ['studente.idS'], ),
    sa.PrimaryKeyConstraint('idE', 'idS')
    )
    op.drop_table('Registrazione_esame')
    op.drop_table('Creazione_esame')
    op.drop_table('Appelli')
    # ### end Alembic commands ###
