"""rimozione foreign key

Revision ID: efcca3c6f947
Revises: 81e76aa32afd
Create Date: 2023-06-10 21:39:32.014773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efcca3c6f947'
down_revision = '81e76aa32afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('esame', schema=None) as batch_op:
        batch_op.drop_column('idP')

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('esame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idP', sa.VARCHAR(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'prova', ['idP'], ['idP'])

    op.create_table('creazione_esame',
    sa.Column('idD', sa.INTEGER(), nullable=False),
    sa.Column('idE', sa.INTEGER(), nullable=False),
    sa.Column('ruolo_docente', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['idD'], ['docente.idD'], ),
    sa.ForeignKeyConstraint(['idE'], ['esame.idE'], ),
    sa.PrimaryKeyConstraint('idD', 'idE')
    )
    op.create_table('registrazione_esame',
    sa.Column('idS', sa.INTEGER(), nullable=False),
    sa.Column('idE', sa.INTEGER(), nullable=False),
    sa.Column('voto', sa.INTEGER(), nullable=True),
    sa.Column('data_superamento', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['idE'], ['esame.idE'], ),
    sa.ForeignKeyConstraint(['idS'], ['studente.idS'], ),
    sa.PrimaryKeyConstraint('idS', 'idE')
    )
    op.create_table('appelli',
    sa.Column('idE', sa.INTEGER(), nullable=False),
    sa.Column('idS', sa.INTEGER(), nullable=False),
    sa.Column('voto', sa.INTEGER(), nullable=True),
    sa.Column('stato_superamento', sa.BOOLEAN(), nullable=True)
    )
    op.drop_table('Registrazione_esame')
    op.drop_table('Creazione_esame')
    op.drop_table('Appelli')
    # ### end Alembic commands ###
