"""rimosso idE da appelli e sistemato foreign key

Revision ID: f841be77acd0
Revises: 39c4822d9fa9
Create Date: 2023-06-11 11:33:21.618811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f841be77acd0'
down_revision = '39c4822d9fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Appelli', schema=None) as batch_op:
        # Drop the existing foreign key constraint
        #batch_op.drop_constraint('fk_appelli_esame_idE', type_='foreignkey')
        
        # Drop the idE column
        batch_op.drop_column('idE')
        
        # Add the new foreign key column
        batch_op.add_column(sa.Column('idP', sa.String(length=100), nullable=True))
        
        # Create the new foreign key constraint
        batch_op.create_foreign_key('fk_appelli_prova_idP', 'prova', ['idP'], ['idP'])

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idP', sa.VARCHAR(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'prova', ['idP'], ['idP'])

    op.create_table('registrazione_esame',
    sa.Column('idS', sa.INTEGER(), nullable=False),
    sa.Column('idE', sa.INTEGER(), nullable=False),
    sa.Column('voto', sa.INTEGER(), nullable=True),
    sa.Column('data_superamento', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['idE'], ['esame.idE'], ),
    sa.ForeignKeyConstraint(['idS'], ['studente.idS'], ),
    sa.PrimaryKeyConstraint('idS', 'idE')
    )
    op.create_table('appelli',
    sa.Column('idE', sa.INTEGER(), nullable=False),
    sa.Column('idS', sa.INTEGER(), nullable=False),
    sa.Column('voto', sa.INTEGER(), nullable=True),
    sa.Column('stato_superamento', sa.BOOLEAN(), nullable=True)
    )
    op.create_table('creazione_esame',
    sa.Column('idD', sa.INTEGER(), nullable=False),
    sa.Column('idE', sa.INTEGER(), nullable=False),
    sa.Column('ruolo_docente', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['idD'], ['docente.idD'], ),
    sa.ForeignKeyConstraint(['idE'], ['esame.idE'], ),
    sa.PrimaryKeyConstraint('idD', 'idE')
    )
    op.drop_table('Appelli')
    op.drop_table('Registrazione_esame')
    op.drop_table('Creazione_esame')
    # ### end Alembic commands ###
